s = set()

n = int(input("Enter the number1:"))
s.add(n)
n = int(input("Enter the number2:"))
s.add(n)
n = int(input("Enter the number3:"))
s.add(n)
n = int(input("Enter the number4:"))
s.add(n)
n = int(input("Enter the number5:"))
s.add(n)
n = int(input("Enter the number6:"))
s.add(n)
n = int(input("Enter the number7:"))
s.add(n)
print(s)


# s = set()
# d = input("enter the number:")
# s.add(int(d))
# d = input("enter the number:")
# s.add(int(d))
# d = input("enter the number:")
# s.add(int(d))
# d = input("enter the number:")
# s.add(int(d))
# d = input("enter the number:")
# s.add(int(d))
# print(s)